name: documentation
run-name: ${{github.event.pull_request.title}}
on:
    schedule:
    # Run everyday at 5:00 AM
    - cron: "0 5 * * *"
jobs:
  daily-markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@1b916f2cf6c36510a6059943104e3c42ce6c16bc
        with:
          use-quiet-mode: 'yes'  
          use-verbose-mode: 'yes'
          config-file: '.mlc.config.json'
          folder-path: '.'
          max-depth: -1
