name: tests

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*"
    paths-ignore:
      - .reuse
      - LICENSES/
      - LICENSE
      - .gitignore
      - "**.md"

  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - .reuse
      - LICENSES/
      - LICENSE
      - .gitignore
      - "**.md"

permissions:
  contents: read
jobs:
 # lint:
############################################################################################
  unit-tests:
    runs-on: ubuntu-latest
    steps:
############################################################################################
    - name: Checkout code
      uses: actions/checkout@v4
############################################################################################
    - name: Set up cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          /home/runner/work/infrastructure-manager/infrastructure-manager/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
############################################################################################
    - name: Set up go environment
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.6
############################################################################################
    - name: Run unit tests
      run: make test
